import { mergeTheme } from './mergeTheme';
import defaultTheme from './default';

const caosTheme = mergeTheme(defaultTheme, {
	typography: {
		fontFamilies: {
			body: '"Rubik", system-ui, -apple-system, sans-serif',
			heading: '"Orbitron", system-ui, -apple-system, sans-serif',
			mono: '"SF Mono", "Cascadia Code", "JetBrains Mono", monospace',
		},
		fontSize: {
			xxs: { fontSizePx: 13, fontSizeRem: 0.8125 },
			xs: { fontSizePx: 15, fontSizeRem: 0.9375 },
			sm: { fontSizePx: 17, fontSizeRem: 1.0625 },
			md: { fontSizePx: 19, fontSizeRem: 1.1875 },
			lg: { fontSizePx: 22, fontSizeRem: 1.375 },
			xl: { fontSizePx: 26, fontSizeRem: 1.625 },
			'2xl': { fontSizePx: 32, fontSizeRem: 2 },
			'3xl': { fontSizePx: 38, fontSizeRem: 2.375 },
			'4xl': { fontSizePx: 50, fontSizeRem: 3.125, letterSpacing: -0.01 },
			'5xl': { fontSizePx: 62, fontSizeRem: 3.875, letterSpacing: -0.015 },
			'6xl': { fontSizePx: 74, fontSizeRem: 4.625, letterSpacing: -0.02 },
		},
	},

	colors: {
		primary_50: '#F5F3EE',
		primary_100: '#E8E4DA',
		primary_200: '#D4CDB8',
		primary_300: '#B8AD94',
		primary_400: '#9C8E70',
		primary_500: '#7D6F52',
		primary_600: '#6B5D43',
		primary_700: '#544A35',
		primary_800: '#3D3628',
		primary_900: '#2A251B',
		primary_950: '#1A170F',

		secondary_50: '#FBF3EE',
		secondary_100: '#F5E4D8',
		secondary_200: '#EDD0BE',
		secondary_300: '#DDB49A',
		secondary_400: '#C99170',
		secondary_500: '#B87450',
		secondary_600: '#9E5E3C',
		secondary_700: '#7A4A2F',
		secondary_800: '#573522',
		secondary_900: '#3A2417',
		secondary_950: '#1F120C',

		neutral_50: '#F7F5F2',
		neutral_100: '#EDE9E3',
		neutral_200: '#DDD7CE',
		neutral_300: '#C4BBB0',
		neutral_400: '#A69C90',
		neutral_500: '#8A7F73',
		neutral_600: '#6E655B',
		neutral_700: '#554D45',
		neutral_800: '#3C3631',
		neutral_900: '#262220',
		neutral_950: '#141211',

		error_50: '#FCF4F2',
		error_100: '#F9EDE9',
		error_200: '#F5DAD3',
		error_300: '#E8B5A7',
		error_400: '#D48A78',
		error_500: '#C06A55',
		error_600: '#A35240',
		error_700: '#7E3E31',
		error_800: '#5A2D23',
		error_900: '#3D1F18',
		error_950: '#21110D',

		info_50: '#F2F5F0',
		info_100: '#E4EAE0',
		info_200: '#C8D5C0',
		info_300: '#A4B99A',
		info_400: '#7E9C72',
		info_500: '#5F8050',
		info_600: '#4A673E',
		info_700: '#384E2F',
		info_800: '#273722',
		info_900: '#1A2517',
		info_950: '#0E140C',

		success_50: '#F0F7F0',
		success_100: '#E0EFE0',
		success_200: '#C0DFC0',
		success_300: '#94C494',
		success_400: '#68A868',
		success_500: '#4A8C4A',
		success_600: '#3A713A',
		success_700: '#2C562C',
		success_800: '#1F3D1F',
		success_900: '#152915',
		success_950: '#0B160B',

		warning_50: '#FDF8ED',
		warning_100: '#FAF0D5',
		warning_200: '#F4DDA8',
		warning_300: '#E8C574',
		warning_400: '#D4A844',
		warning_500: '#B88E2A',
		warning_600: '#94721F',
		warning_700: '#705618',
		warning_800: '#4E3C11',
		warning_900: '#33270C',
		warning_950: '#1A1406',
	},

	contracts: {
		actions: {
			primary: defaultTheme.contracts.actions.secondary,
			secondary: defaultTheme.contracts.actions.primary,
			ghost: defaultTheme.contracts.actions.ghost,
			link: defaultTheme.contracts.actions.link,
			tertiary: defaultTheme.contracts.actions.tertiary,
		},
		feedback: {
			error: {
				...defaultTheme.contracts.feedback.warning,
				borderWidth: 2,
				borderRadius: { type: 'radii' as const, value: '2xl' },
			},
			success: {
				...defaultTheme.contracts.feedback.success,
				borderWidth: 2,
				borderRadius: { type: 'radii' as const, value: '2xl' },
			},
			warning: {
				...defaultTheme.contracts.feedback.error,
				borderWidth: 2,
				borderRadius: { type: 'radii' as const, value: '2xl' },
			},
			info: {
				...defaultTheme.contracts.feedback.info,
				borderWidth: 2,
				borderRadius: { type: 'radii' as const, value: '2xl' },
			},
		},
		surfaces: {
			base: defaultTheme.contracts.surfaces.alt,
			alt: defaultTheme.contracts.surfaces.base,
			raised: defaultTheme.contracts.surfaces.raised,
			sunken: defaultTheme.contracts.surfaces.sunken,
			inverse: defaultTheme.contracts.surfaces.inverse,
			brand: defaultTheme.contracts.surfaces.brand,
		},

		inputField: {
			bg: 'bg-primary',
			on: 'text-primary',
			border: 'border-primary',
			placeholder: 'text-placeholder',
			bgHover: 'bg-primary',
			borderHover: 'border-brand',
			bgFocus: 'bg-primary',
			borderFocus: 'border-brand',
			onFocus: 'text-primary',
			bgDisabled: 'bg-tertiary',
			onDisabled: 'text-quaternary',
			borderDisabled: 'border-secondary',
			borderError: 'border-error',
			onError: 'text-error-primary',
			borderSuccess: 'utility-success-500',
			onSuccess: 'text-success-primary',
		},

		selectionControl: {
			bg: 'bg-primary',
			border: 'border-primary',
			bgChecked: 'bg-brand-solid',
			borderChecked: 'border-brand',
			onChecked: 'text-white',
			bgHover: 'bg-primary',
			borderHover: 'border-brand',
			bgDisabled: 'bg-tertiary',
			borderDisabled: 'border-secondary',
			onDisabled: 'text-quaternary',
			borderError: 'border-error',
		},

		toggle: {
			trackBg: 'bg-tertiary',
			trackBgChecked: 'bg-brand-solid',
			trackBorder: 'border-primary',
			thumbColor: 'text-white',
			thumbColorChecked: 'text-white',
			bgHover: 'bg-quaternary',
			trackBgCheckedHover: 'bg-brand-solid_hover',
			bgDisabled: 'bg-tertiary',
			trackBgDisabled: 'bg-quaternary',
			thumbDisabled: 'text-quaternary',
			borderError: 'border-error',
		},

		components: {
			buttonBorderRadii: { type: 'radii' as const, value: 'full' },
			cardBorderRadii: { type: 'radii' as const, value: '2xl' },
			inputBorderRadii: { type: 'radii' as const, value: 'xl' },
		},
	},

	shadows: {
		none: {
			layers: [{ offsetX: 0, offsetY: 0, blurRadius: 0, spreadRadius: 0, opacity: 0 }],
			color: { light: 'transparent', dark: 'transparent' },
		},
		xs: {
			layers: [{ offsetX: 0, offsetY: 2, blurRadius: 4, spreadRadius: 0, opacity: 0.06 }],
			color: { light: 'neutral_600', dark: 'neutral_400' },
		},
		sm: {
			layers: [
				{ offsetX: 0, offsetY: 2, blurRadius: 6, spreadRadius: 0, opacity: 0.08 },
				{ offsetX: 0, offsetY: 1, blurRadius: 3, spreadRadius: -1, opacity: 0.06 },
			],
			color: { light: 'neutral_600', dark: 'neutral_400' },
		},
		md: {
			layers: [
				{ offsetX: 0, offsetY: 4, blurRadius: 10, spreadRadius: -2, opacity: 0.1 },
				{ offsetX: 0, offsetY: 2, blurRadius: 6, spreadRadius: -2, opacity: 0.06 },
			],
			color: { light: 'neutral_700', dark: 'neutral_300' },
		},
		lg: {
			layers: [
				{ offsetX: 0, offsetY: 8, blurRadius: 20, spreadRadius: -4, opacity: 0.1 },
				{ offsetX: 0, offsetY: 4, blurRadius: 8, spreadRadius: -2, opacity: 0.04 },
				{ offsetX: 0, offsetY: 2, blurRadius: 4, spreadRadius: -1, opacity: 0.03 },
			],
			color: { light: 'neutral_700', dark: 'neutral_300' },
		},
		xl: {
			layers: [
				{ offsetX: 0, offsetY: 12, blurRadius: 28, spreadRadius: -6, opacity: 0.1 },
				{ offsetX: 0, offsetY: 6, blurRadius: 12, spreadRadius: -4, opacity: 0.04 },
				{ offsetX: 0, offsetY: 3, blurRadius: 6, spreadRadius: -2, opacity: 0.03 },
			],
			color: { light: 'neutral_700', dark: 'neutral_300' },
		},
		'2xl': {
			layers: [
				{ offsetX: 0, offsetY: 16, blurRadius: 40, spreadRadius: -8, opacity: 0.14 },
				{ offsetX: 0, offsetY: 6, blurRadius: 8, spreadRadius: -4, opacity: 0.04 },
			],
			color: { light: 'neutral_800', dark: 'neutral_200' },
		},
		'3xl': {
			layers: [
				{ offsetX: 0, offsetY: 20, blurRadius: 52, spreadRadius: -10, opacity: 0.16 },
				{ offsetX: 0, offsetY: 8, blurRadius: 10, spreadRadius: -4, opacity: 0.05 },
			],
			color: { light: 'neutral_800', dark: 'neutral_200' },
		},
	},
});

export default caosTheme;
