import { TokensSchema, type Tokens } from '@repo/foundations';

const defaultThemeTokens: Tokens = {
	spacing: {
		none: 0,
		xxs: 2,
		xs: 4,
		sm: 6,
		md: 8,
		lg: 12,
		xl: 16,
		'2xl': 20,
		'3xl': 24,
		'4xl': 32,
		'5xl': 40,
		'6xl': 48,
		'7xl': 64,
		'8xl': 80,
		'9xl': 96,
		'10xl': 128,
		'11xl': 160,
	},
	radii: {
		none: 0,
		xxs: 2,
		xs: 4,
		sm: 6,
		md: 8,
		lg: 10,
		xl: 12,
		'2xl': 16,
		'3xl': 20,
		'4xl': 24,
		'5xl': 32,
		'6xl': 40,
		'7xl': 48,
		full: 9999,
	},
	widths: {
		xxs: 320,
		xs: 384,
		sm: 480,
		md: 560,
		lg: 640,
		xl: 768,
		'2xl': 1024,
		'3xl': 1280,
		'4xl': 1440,
		'5xl': 1600,
		'6xl': 1920,
	},
	layout: {
		none: 0,
		sm: 16,
		md: 32,
		lg: 48,
		xl: 64,
	},

	colors: {
		white: '#FFFFFF',
		black: '#000000',
		transparent: 'transparent',

		primary_50: '#F0F9FF',
		primary_100: '#E0F2FE',
		primary_200: '#BAE6FD',
		primary_300: '#7DD3FC',
		primary_400: '#38BDF8',
		primary_500: '#0EA5E9',
		primary_600: '#0284C7',
		primary_700: '#0369A1',
		primary_800: '#075985',
		primary_900: '#0C4A6E',
		primary_950: '#082F49',

		secondary_50: '#FCE7E1',
		secondary_100: '#f7c1b2',
		secondary_200: '#f49b8a',
		secondary_300: '#f07562',
		secondary_400: '#ed4f3a',
		secondary_500: '#e92a12',
		secondary_600: '#b21f0e',
		secondary_700: '#7a150a',
		secondary_800: '#430b05',
		secondary_900: '#1a0201',
		secondary_950: '#0A0100',

		neutral_50: '#F9FAFB',
		neutral_100: '#F3F4F6',
		neutral_200: '#E5E7EB',
		neutral_300: '#D1D5DB',
		neutral_400: '#9CA3AF',
		neutral_500: '#6B7280',
		neutral_600: '#4B5563',
		neutral_700: '#374151',
		neutral_800: '#1F2937',
		neutral_900: '#111827',
		neutral_950: '#030712',

		error_50: '#FCF4F2',
		error_100: '#F9F0EE',
		error_200: '#F9E1DC',
		error_300: '#FBBDB0',
		error_400: '#FA8B75',
		error_500: '#E9553C',
		error_600: '#D63D27',
		error_700: '#992A1A',
		error_800: '#6E2418',
		error_900: '#4A1C14',
		error_950: '#2A0F0B',

		info_50: '#F2F9FE',
		info_100: '#E8F4FE',
		info_200: '#D2E8FB',
		info_300: '#A8D1F5',
		info_400: '#6CB0ED',
		info_500: '#278AE3',
		info_600: '#0074DE',
		info_700: '#00529E',
		info_800: '#003E76',
		info_900: '#002A51',
		info_950: '#001A33',

		success_50: '#F0FBF0',
		success_100: '#E5F7E6',
		success_200: '#C4F1C5',
		success_300: '#72E37E',
		success_400: '#00C445',
		success_500: '#069C35',
		success_600: '#1A8732',
		success_700: '#245D2A',
		success_800: '#214423',
		success_900: '#1B2F1B',
		success_950: '#0E1A0E',

		warning_50: '#FEF7E8',
		warning_100: '#FEF0DB',
		warning_200: '#FFE1B4',
		warning_300: '#FFC163',
		warning_400: '#EE9609',
		warning_500: '#BE7704',
		warning_600: '#A3670F',
		warning_700: '#704A18',
		warning_800: '#513817',
		warning_900: '#372714',
		warning_950: '#1E160A',
	},
	typography: {
		fontFamilies: {
			body: '"Inter", system-ui, -apple-system, sans-serif',
			heading: '"Inter", system-ui, -apple-system, sans-serif',
			mono: '"SF Mono", "Cascadia Code", "JetBrains Mono", monospace',
		},
		fontSize: {
			xxs: { fontSizePx: 12, fontSizeRem: 0.75 },
			xs: { fontSizePx: 14, fontSizeRem: 0.875 },
			sm: { fontSizePx: 16, fontSizeRem: 1 },
			md: { fontSizePx: 18, fontSizeRem: 1.125 },
			lg: { fontSizePx: 20, fontSizeRem: 1.25 },
			xl: { fontSizePx: 24, fontSizeRem: 1.5 },
			'2xl': { fontSizePx: 30, fontSizeRem: 1.875 },
			'3xl': { fontSizePx: 36, fontSizeRem: 2.25 },
			'4xl': {
				fontSizePx: 48,
				fontSizeRem: 3,
				letterSpacing: -0.02,
			},
			'5xl': {
				fontSizePx: 60,
				fontSizeRem: 3.75,
				letterSpacing: -0.02,
			},
			'6xl': {
				fontSizePx: 72,
				fontSizeRem: 4.5,
				letterSpacing: -0.02,
			},
		},
		fontWeight: {
			thin: 100,
			light: 300,
			regular: 400,
			medium: 500,
			semibold: 600,
			bold: 700,
			black: 900,
		},
		lineHeight: {
			none: 1,
			tight: 1.25,
			normal: 1.5,
			relaxed: 1.75,
			loose: 2,
		},
		letterSpacing: {
			tighter: -0.05,
			tight: -0.025,
			normal: 0,
			wide: 0.025,
			wider: 0.05,
			widest: 0.1,
		},
	},

	colorTokens: {
		text: {
			'text-primary': { light: 'neutral_900', dark: 'neutral_50' },
			'text-primary_on-brand': { light: 'white', dark: 'neutral_50' },
			'text-secondary': { light: 'neutral_700', dark: 'neutral_300' },
			'text-secondary_hover': { light: 'neutral_800', dark: 'neutral_200' },
			'text-secondary_on-brand': { light: 'primary_200', dark: 'neutral_300' },
			'text-tertiary': { light: 'neutral_600', dark: 'neutral_400' },
			'text-tertiary_hover': { light: 'neutral_700', dark: 'neutral_300' },
			'text-tertiary_on-brand': { light: 'primary_200', dark: 'neutral_400' },
			'text-quaternary': { light: 'neutral_500', dark: 'neutral_400' },
			'text-quaternary_on-brand': { light: 'primary_300', dark: 'neutral_400' },
			'text-white': { light: 'white', dark: 'white' },
			'text-placeholder': { light: 'neutral_500', dark: 'neutral_400' },
			'text-brand-primary': { light: 'primary_900', dark: 'neutral_50' },
			'text-brand-secondary': { light: 'primary_700', dark: 'neutral_300' },
			'text-brand-secondary_hover': { light: 'primary_800', dark: 'neutral_200' },
			'text-brand-tertiary': { light: 'primary_600', dark: 'neutral_400' },
			'text-brand-tertiary_alt': { light: 'primary_500', dark: 'neutral_50' },
			'text-error-primary': { light: 'error_600', dark: 'error_400' },
			'text-warning-primary': { light: 'warning_600', dark: 'warning_400' },
			'text-success-primary': { light: 'success_600', dark: 'success_400' },
			'text-info-primary': { light: 'info_600', dark: 'info_400' },
		},
		border: {
			'border-primary': { light: 'neutral_300', dark: 'neutral_700' },
			'border-secondary': { light: 'neutral_200', dark: 'neutral_800' },
			'border-secondary_alt': {
				light: { base: 'black', alpha: 0.1 },
				dark: 'neutral_800',
			},
			'border-tertiary': { light: 'neutral_100', dark: 'neutral_800' },
			'border-quaternary': { light: 'neutral_500', dark: 'neutral_400' },
			'border-brand': { light: 'primary_500', dark: 'primary_400' },
			'border-brand_alt': { light: 'primary_600', dark: 'neutral_700' },
			'border-error': { light: 'error_500', dark: 'error_400' },
			'border-error_subtle': { light: 'error_300', dark: 'error_500' },
		},
		fg: {
			'fg-primary': { light: 'neutral_900', dark: 'white' },
			'fg-secondary': { light: 'neutral_700', dark: 'neutral_300' },
			'fg-secondary_hover': { light: 'neutral_800', dark: 'neutral_200' },
			'fg-tertiary': { light: 'neutral_600', dark: 'neutral_400' },
			'fg-tertiary_hover': { light: 'neutral_700', dark: 'neutral_300' },
			'fg-quaternary': { light: 'neutral_400', dark: 'neutral_500' },
			'fg-quaternary_hover': { light: 'neutral_500', dark: 'neutral_400' },
			'fg-white': { light: 'white', dark: 'white' },
			'fg-brand-primary': { light: 'primary_600', dark: 'primary_500' },
			'fg-brand-primary_alt': { light: 'primary_600', dark: 'neutral_300' },
			'fg-brand-secondary': { light: 'primary_500', dark: 'primary_500' },
			'fg-brand-secondary_alt': { light: 'primary_500', dark: 'neutral_400' },
			'fg-error-primary': { light: 'error_600', dark: 'error_500' },
			'fg-error-secondary': { light: 'error_500', dark: 'error_400' },
			'fg-warning-primary': { light: 'warning_600', dark: 'warning_500' },
			'fg-warning-secondary': { light: 'warning_500', dark: 'warning_400' },
			'fg-success-primary': { light: 'success_600', dark: 'success_500' },
			'fg-success-secondary': { light: 'success_500', dark: 'success_400' },
			'fg-info-primary': { light: 'info_600', dark: 'info_500' },
			'fg-info-secondary': { light: 'info_500', dark: 'info_400' },
		},
		bg: {
			'bg-primary': { light: 'white', dark: 'neutral_950' },
			'bg-primary_alt': { light: 'white', dark: 'neutral_900' },
			'bg-primary_hover': { light: 'neutral_50', dark: 'neutral_900' },
			'bg-primary-solid': { light: 'neutral_950', dark: 'neutral_800' },
			'bg-secondary': { light: 'neutral_50', dark: 'neutral_900' },
			'bg-secondary_alt': { light: 'neutral_50', dark: 'neutral_950' },
			'bg-secondary_hover': { light: 'neutral_100', dark: 'neutral_800' },
			'bg-secondary-solid': { light: 'neutral_600', dark: 'neutral_600' },
			'bg-tertiary': { light: 'neutral_100', dark: 'neutral_800' },
			'bg-quaternary': { light: 'neutral_200', dark: 'neutral_700' },
			'bg-overlay': { light: 'neutral_950', dark: 'primary_800' },
			'bg-brand-primary': { light: 'primary_50', dark: 'primary_500' },
			'bg-brand-primary_alt': { light: 'primary_50', dark: 'neutral_800' },
			'bg-brand-secondary': { light: 'primary_100', dark: 'neutral_600' },
			'bg-brand-solid': { light: 'primary_600', dark: 'primary_600' },
			'bg-brand-solid_hover': { light: 'primary_700', dark: 'primary_500' },
			'bg-brand-section': { light: 'primary_800', dark: 'neutral_800' },
			'bg-brand-section_subtle': { light: 'primary_700', dark: 'neutral_950' },
			'bg-error-primary': { light: 'error_50', dark: 'error_950' },
			'bg-error-secondary': { light: 'error_100', dark: 'error_600' },
			'bg-error-solid': { light: 'error_600', dark: 'error_600' },
			'bg-error-solid_hover': { light: 'error_700', dark: 'error_500' },
			'bg-warning-primary': { light: 'warning_50', dark: 'warning_950' },
			'bg-warning-secondary': { light: 'warning_100', dark: 'warning_600' },
			'bg-warning-solid': { light: 'warning_100', dark: 'warning_600' },
			'bg-warning-solid_hover': { light: 'warning_700', dark: 'warning_500' },
			'bg-success-primary': { light: 'success_50', dark: 'success_950' },
			'bg-success-secondary': { light: 'success_50', dark: 'success_900' },
			'bg-success-solid': { light: 'success_100', dark: 'success_600' },
			'bg-success-solid_hover': { light: 'success_700', dark: 'success_500' },
			'bg-info-primary': { light: 'info_50', dark: 'info_950' },
			'bg-info-secondary': { light: 'info_50', dark: 'info_900' },
			'bg-info-solid': { light: 'info_100', dark: 'info_600' },
			'bg-info-solid_hover': { light: 'info_700', dark: 'info_500' },
		},
		utility: {
			'utility-neutral-50': { light: 'neutral_50', dark: 'neutral_900' },
			'utility-neutral-100': { light: 'neutral_100', dark: 'neutral_800' },
			'utility-neutral-200': { light: 'neutral_200', dark: 'neutral_700' },
			'utility-neutral-300': { light: 'neutral_300', dark: 'neutral_700' },
			'utility-neutral-400': { light: 'neutral_400', dark: 'neutral_600' },
			'utility-neutral-500': { light: 'neutral_500', dark: 'neutral_500' },
			'utility-neutral-600': { light: 'neutral_600', dark: 'neutral_400' },
			'utility-neutral-700': { light: 'neutral_700', dark: 'neutral_300' },
			'utility-neutral-800': { light: 'neutral_800', dark: 'neutral_200' },
			'utility-neutral-900': { light: 'neutral_900', dark: 'neutral_100' },

			'utility-primary-50': { light: 'primary_50', dark: 'primary_950' },
			'utility-primary-50_alt': { light: 'primary_50', dark: 'neutral_900' },
			'utility-primary-100': { light: 'primary_100', dark: 'primary_900' },
			'utility-primary-100_alt': { light: 'primary_100', dark: 'neutral_800' },
			'utility-primary-200': { light: 'primary_200', dark: 'primary_800' },
			'utility-primary-200_alt': { light: 'primary_200', dark: 'neutral_700' },
			'utility-primary-300': { light: 'primary_300', dark: 'primary_700' },
			'utility-primary-300_alt': { light: 'primary_300', dark: 'neutral_700' },
			'utility-primary-400': { light: 'primary_400', dark: 'primary_600' },
			'utility-primary-400_alt': { light: 'primary_400', dark: 'neutral_600' },
			'utility-primary-500': { light: 'primary_500', dark: 'primary_500' },
			'utility-primary-500_alt': { light: 'primary_500', dark: 'neutral_500' },
			'utility-primary-600': { light: 'primary_600', dark: 'primary_400' },
			'utility-primary-600_alt': { light: 'primary_600', dark: 'neutral_400' },
			'utility-primary-700': { light: 'primary_700', dark: 'primary_300' },
			'utility-primary-700_alt': { light: 'primary_700', dark: 'neutral_300' },
			'utility-primary-800': { light: 'primary_800', dark: 'primary_200' },
			'utility-primary-800_alt': { light: 'primary_800', dark: 'neutral_200' },
			'utility-primary-900': { light: 'primary_900', dark: 'primary_100' },
			'utility-primary-900_alt': { light: 'primary_900', dark: 'neutral_100' },

			'utility-error-50': { light: 'error_50', dark: 'error_950' },
			'utility-error-100': { light: 'error_100', dark: 'error_900' },
			'utility-error-200': { light: 'error_200', dark: 'error_800' },
			'utility-error-300': { light: 'error_300', dark: 'error_700' },
			'utility-error-400': { light: 'error_400', dark: 'error_600' },
			'utility-error-500': { light: 'error_500', dark: 'error_500' },
			'utility-error-600': { light: 'error_600', dark: 'error_400' },
			'utility-error-700': { light: 'error_700', dark: 'error_300' },

			'utility-warning-50': { light: 'warning_50', dark: 'warning_950' },
			'utility-warning-100': { light: 'warning_100', dark: 'warning_900' },
			'utility-warning-200': { light: 'warning_200', dark: 'warning_800' },
			'utility-warning-300': { light: 'warning_300', dark: 'warning_700' },
			'utility-warning-400': { light: 'warning_400', dark: 'warning_600' },
			'utility-warning-500': { light: 'warning_500', dark: 'warning_500' },
			'utility-warning-600': { light: 'warning_600', dark: 'warning_400' },
			'utility-warning-700': { light: 'warning_700', dark: 'warning_300' },

			'utility-success-50': { light: 'success_50', dark: 'success_950' },
			'utility-success-100': { light: 'success_100', dark: 'success_900' },
			'utility-success-200': { light: 'success_200', dark: 'success_800' },
			'utility-success-300': { light: 'success_300', dark: 'success_700' },
			'utility-success-400': { light: 'success_400', dark: 'success_600' },
			'utility-success-500': { light: 'success_500', dark: 'success_500' },
			'utility-success-600': { light: 'success_600', dark: 'success_400' },
			'utility-success-700': { light: 'success_700', dark: 'success_300' },

			'utility-info-50': { light: 'info_50', dark: 'info_950' },
			'utility-info-100': { light: 'info_100', dark: 'info_900' },
			'utility-info-200': { light: 'info_200', dark: 'info_800' },
			'utility-info-300': { light: 'info_300', dark: 'info_700' },
			'utility-info-400': { light: 'info_400', dark: 'info_600' },
			'utility-info-500': { light: 'info_500', dark: 'info_500' },
			'utility-info-600': { light: 'info_600', dark: 'info_400' },
			'utility-info-700': { light: 'info_700', dark: 'info_300' },
		},
	},

	shadows: {
		none: {
			layers: [{ offsetX: 0, offsetY: 0, blurRadius: 0, spreadRadius: 0, opacity: 0 }],
			color: { light: 'transparent', dark: 'transparent' },
		},

		xs: {
			layers: [{ offsetX: 0, offsetY: 1, blurRadius: 2, spreadRadius: 0, opacity: 0.05 }],
			color: { light: 'black', dark: 'white' },
		},

		sm: {
			layers: [
				{ offsetX: 0, offsetY: 1, blurRadius: 3, spreadRadius: 0, opacity: 0.1 },
				{ offsetX: 0, offsetY: 1, blurRadius: 2, spreadRadius: -1, opacity: 0.1 },
			],
			color: { light: 'black', dark: 'white' },
		},

		md: {
			layers: [
				{ offsetX: 0, offsetY: 4, blurRadius: 6, spreadRadius: -1, opacity: 0.1 },
				{ offsetX: 0, offsetY: 2, blurRadius: 4, spreadRadius: -2, opacity: 0.06 },
			],
			color: { light: 'black', dark: 'white' },
		},

		lg: {
			layers: [
				{ offsetX: 0, offsetY: 12, blurRadius: 16, spreadRadius: -4, opacity: 0.08 },
				{ offsetX: 0, offsetY: 4, blurRadius: 6, spreadRadius: -2, opacity: 0.03 },
				{ offsetX: 0, offsetY: 2, blurRadius: 2, spreadRadius: -1, opacity: 0.04 },
			],
			color: { light: 'black', dark: 'white' },
		},

		xl: {
			layers: [
				{ offsetX: 0, offsetY: 20, blurRadius: 24, spreadRadius: -4, opacity: 0.08 },
				{ offsetX: 0, offsetY: 8, blurRadius: 8, spreadRadius: -4, opacity: 0.03 },
				{ offsetX: 0, offsetY: 3, blurRadius: 3, spreadRadius: -1.5, opacity: 0.04 },
			],
			color: { light: 'black', dark: 'white' },
		},

		'2xl': {
			layers: [
				{ offsetX: 0, offsetY: 24, blurRadius: 48, spreadRadius: -12, opacity: 0.18 },
				{ offsetX: 0, offsetY: 4, blurRadius: 4, spreadRadius: -2, opacity: 0.04 },
			],
			color: { light: 'black', dark: 'white' },
		},

		'3xl': {
			layers: [
				{ offsetX: 0, offsetY: 32, blurRadius: 64, spreadRadius: -12, opacity: 0.14 },
				{ offsetX: 0, offsetY: 5, blurRadius: 5, spreadRadius: -2.5, opacity: 0.04 },
			],
			color: { light: 'black', dark: 'white' },
		},
	},
	focusRing: {
		'focus-ring': { color: { light: 'primary_500', dark: 'primary_400' } },
		'focus-ring-error': { color: { light: 'error_500', dark: 'error_500' } },
		'focus-ring-shadow-xs': {
			color: { light: 'primary_500', dark: 'primary_400' },
			shadow: 'xs',
		},
		'focus-ring-shadow-sm': {
			color: { light: 'primary_500', dark: 'primary_400' },
			shadow: 'sm',
		},
		'focus-ring-error-shadow-xs': {
			color: { light: 'error_500', dark: 'error_500' },
			shadow: 'xs',
		},
	},

	gradients: {
		neutral_600_500_90: {
			type: 'linear',
			angle: 90,
			stops: [
				{ color: 'neutral_600', position: 0 },
				{ color: 'neutral_500', position: 100 },
			],
		},
		neutral_700_600_45: {
			type: 'linear',
			angle: 45,
			stops: [
				{ color: 'neutral_700', position: 0 },
				{ color: 'neutral_600', position: 100 },
			],
		},
		neutral_800_600_45: {
			type: 'linear',
			angle: 45,
			stops: [
				{ color: 'neutral_800', position: 0 },
				{ color: 'neutral_600', position: 100 },
			],
		},
		neutral_800_600_90: {
			type: 'linear',
			angle: 90,
			stops: [
				{ color: 'neutral_800', position: 0 },
				{ color: 'neutral_600', position: 100 },
			],
		},
		neutral_800_700_26_5: {
			type: 'linear',
			angle: 26.5,
			stops: [
				{ color: 'neutral_800', position: 0 },
				{ color: 'neutral_700', position: 100 },
			],
		},
		neutral_900_600_45: {
			type: 'linear',
			angle: 45,
			stops: [
				{ color: 'neutral_900', position: 0 },
				{ color: 'neutral_600', position: 100 },
			],
		},
		neutral_900_700_45: {
			type: 'linear',
			angle: 45,
			stops: [
				{ color: 'neutral_900', position: 0 },
				{ color: 'neutral_700', position: 100 },
			],
		},
		neutral_50_white_180: {
			type: 'linear',
			angle: 180,
			stops: [
				{ color: 'neutral_50', position: 0 },
				{ color: 'white', position: 100 },
			],
		},
		neutral_100_white_180: {
			type: 'linear',
			angle: 180,
			stops: [
				{ color: 'neutral_100', position: 0 },
				{ color: 'white', position: 100 },
			],
		},
		neutral_100_50_180: {
			type: 'linear',
			angle: 180,
			stops: [
				{ color: 'neutral_100', position: 0 },
				{ color: 'neutral_50', position: 100 },
			],
		},
		neutral_200_50_180: {
			type: 'linear',
			angle: 180,
			stops: [
				{ color: 'neutral_200', position: 0 },
				{ color: 'neutral_50', position: 100 },
			],
		},
		neutral_200_100_180: {
			type: 'linear',
			angle: 180,
			stops: [
				{ color: 'neutral_200', position: 0 },
				{ color: 'neutral_100', position: 100 },
			],
		},
		white_neutral_50_180: {
			type: 'linear',
			angle: 180,
			stops: [
				{ color: 'white', position: 0 },
				{ color: 'neutral_50', position: 100 },
			],
		},
		primary_600_500_90: {
			type: 'linear',
			angle: 90,
			stops: [
				{ color: 'primary_600', position: 0 },
				{ color: 'primary_500', position: 100 },
			],
		},
		primary_700_600_45: {
			type: 'linear',
			angle: 45,
			stops: [
				{ color: 'primary_700', position: 0 },
				{ color: 'primary_600', position: 100 },
			],
		},
		primary_800_600_45: {
			type: 'linear',
			angle: 45,
			stops: [
				{ color: 'primary_800', position: 0 },
				{ color: 'primary_600', position: 100 },
			],
		},
		primary_800_600_90: {
			type: 'linear',
			angle: 90,
			stops: [
				{ color: 'primary_800', position: 0 },
				{ color: 'primary_600', position: 100 },
			],
		},
		primary_800_700_26_5: {
			type: 'linear',
			angle: 26.5,
			stops: [
				{ color: 'primary_800', position: 0 },
				{ color: 'primary_700', position: 100 },
			],
		},
		primary_900_600_45: {
			type: 'linear',
			angle: 45,
			stops: [
				{ color: 'primary_900', position: 0 },
				{ color: 'primary_600', position: 100 },
			],
		},
		primary_900_700_45: {
			type: 'linear',
			angle: 45,
			stops: [
				{ color: 'primary_900', position: 0 },
				{ color: 'primary_700', position: 100 },
			],
		},
	},

	breakpoints: {
		mobile: 0,
		tablet: 600,
		desktop: 1024,
		wide: 1440,
		ultra: 1920,
	},

	grid: {
		mobile: {
			columns: 4,
			gutter: 'sm', // 16px
			margin: 'sm', // 16px
			maxWidth: 'sm', // 480px
		},

		tablet: {
			columns: 6,
			gutter: 'md', // 32px
			margin: 'md', // 32px
			maxWidth: 'xl', // 768px
		},

		desktop: {
			columns: 12,
			gutter: 'md', // 32px
			margin: 'md', // 32px
			maxWidth: '3xl', // 1280px
		},

		wide: {
			columns: 12,
			gutter: 'md', // 32px
			margin: 'lg', // 48px
			maxWidth: '4xl', // 1440px
		},

		ultra: {
			columns: 12,
			gutter: 'lg', // 48px
			margin: 'xl', // 64px
			maxWidth: '5xl', // 1600px
		},
	},

	contracts: {
		actions: {
			primary: {
				bg: 'bg-brand-solid',
				on: 'text-white',
				border: 'border-brand',
				bgHover: 'bg-brand-solid_hover',
				onHover: 'text-white',
				bgActive: 'bg-brand-solid_hover',
				onActive: 'text-white',
				bgFocus: 'bg-brand-solid',
				onFocus: 'text-white',
				borderFocus: 'border-brand',
				bgDisabled: 'bg-quaternary',
				onDisabled: 'text-quaternary',
				borderDisabled: 'border-quaternary',
			},
			secondary: {
				bg: 'bg-tertiary',
				on: 'text-primary',
				border: 'border-primary',
				bgHover: 'bg-quaternary',
				onHover: 'text-primary',
				bgActive: 'bg-quaternary',
				onActive: 'text-primary',
				bgFocus: 'bg-tertiary',
				onFocus: 'text-primary',
				borderFocus: 'border-primary',
				bgDisabled: 'bg-tertiary',
				onDisabled: 'text-quaternary',
				borderDisabled: 'border-quaternary',
			},
			ghost: {
				bg: 'transparent',
				on: 'text-primary',
				border: 'border-primary',
				bgHover: 'bg-tertiary',
				onHover: 'text-primary',
				bgActive: 'bg-quaternary',
				onActive: 'text-primary',
				bgFocus: 'bg-tertiary',
				onFocus: 'text-primary',
				borderFocus: 'border-primary',
				bgDisabled: 'transparent',
				onDisabled: 'text-quaternary',
				borderDisabled: 'transparent',
			},
			link: {
				on: 'text-brand-tertiary',
				onHover: 'text-brand-secondary_hover',
				onActive: 'text-brand-tertiary',
				onFocus: 'text-brand-secondary_hover',
				onDisabled: 'text-quaternary',
			},
			tertiary: {
				bg: 'white',
				on: 'bg-brand-solid',
				border: 'bg-brand-solid',
				bgHover: 'bg-tertiary',
				onHover: 'bg-brand-solid',
				bgActive: 'bg-tertiary',
				onActive: 'bg-brand-solid',
				bgFocus: 'white',
				onFocus: 'bg-brand-solid',
				borderFocus: 'white',
				bgDisabled: 'bg-tertiary',
				onDisabled: 'text-quaternary',
				borderDisabled: 'bg-tertiary',
			},
		},

		feedback: {
			error: {
				bg: 'bg-error-primary',
				on: 'text-error-primary',
				border: 'border-error',
				borderWidth: 1,
				borderRadius: { type: 'radii' as const, value: 'lg' },
				bgInverse: 'bg-error-solid',
				onInverse: 'fg-error-secondary',
			},
			success: {
				bg: 'bg-success-primary',
				on: 'text-success-primary',
				border: 'utility-success-300',
				borderWidth: 1,
				borderRadius: { type: 'radii' as const, value: 'lg' },
				bgInverse: 'bg-success-solid',
				onInverse: 'fg-success-secondary',
			},
			warning: {
				bg: 'bg-warning-primary',
				on: 'text-warning-primary',
				border: 'utility-warning-300',
				borderWidth: 1,
				borderRadius: { type: 'radii' as const, value: 'lg' },
				bgInverse: 'bg-warning-solid',
				onInverse: 'fg-warning-secondary',
			},
			info: {
				bg: 'bg-info-primary',
				on: 'text-info-primary',
				border: 'utility-info-300',
				borderWidth: 1,
				borderRadius: { type: 'radii' as const, value: 'lg' },
				bgInverse: 'bg-info-solid',
				onInverse: 'fg-info-secondary',
			},
		},

		surfaces: {
			base: { bg: 'bg-primary', on: 'text-primary', border: 'border-primary' },
			alt: { bg: 'bg-secondary', on: 'text-primary', border: 'border-primary' },
			raised: { bg: 'bg-tertiary', on: 'text-primary', border: 'border-primary' },
			sunken: { bg: 'bg-quaternary', on: 'text-primary', border: 'border-primary' },
			inverse: { bg: 'bg-primary-solid', on: 'text-white', border: 'border-primary' },
			brand: {
				bg: 'bg-brand-secondary',
				on: 'text-brand-tertiary',
				border: 'border-brand',
			},
		},

		typography: {
			h1: {
				fontSize: '6xl',
				fontWeight: 'bold',
				lineHeight: 'normal',
				letterSpacing: 'tight',
				fontFamily: 'heading',
				color: 'text-primary',
			},
			h2: {
				fontSize: '5xl',
				fontWeight: 'bold',
				lineHeight: 'normal',
				fontFamily: 'heading',
				color: 'text-primary',
			},
			h3: {
				fontSize: '4xl',
				fontWeight: 'semibold',
				lineHeight: 'normal',
				fontFamily: 'heading',
				color: 'text-primary',
			},
			h4: {
				fontSize: '3xl',
				fontWeight: 'semibold',
				lineHeight: 'normal',
				fontFamily: 'heading',
				color: 'text-primary',
			},
			p: {
				fontSize: 'md',
				fontWeight: 'regular',
				lineHeight: 'normal',
				fontFamily: 'body',
				color: 'text-primary',
			},
			caption: {
				fontSize: 'xs',
				fontWeight: 'medium',
				lineHeight: 'normal',
				fontFamily: 'body',
				color: 'text-primary',
			},
			label: {
				fontSize: 'sm',
				fontWeight: 'medium',
				lineHeight: 'tight',
				fontFamily: 'body',
				color: 'text-primary',
			},
			overline: {
				fontSize: 'xs',
				fontWeight: 'semibold',
				lineHeight: 'tight',
				letterSpacing: 'wider',
				fontFamily: 'body',
				color: 'text-primary',
			},
		},

		inputField: {
			bg: 'bg-primary',
			on: 'text-primary',
			border: 'border-primary',
			placeholder: 'text-placeholder',
			bgHover: 'bg-primary',
			borderHover: 'border-brand',
			bgFocus: 'bg-primary',
			borderFocus: 'border-brand',
			onFocus: 'text-primary',
			bgDisabled: 'bg-tertiary',
			onDisabled: 'text-quaternary',
			borderDisabled: 'border-secondary',
			borderError: 'border-error',
			onError: 'text-error-primary',
			borderSuccess: 'utility-success-500',
			onSuccess: 'text-success-primary',
		},

		selectionControl: {
			bg: 'bg-primary',
			border: 'border-primary',
			bgChecked: 'bg-brand-solid',
			borderChecked: 'border-brand',
			onChecked: 'text-white',
			bgHover: 'bg-primary',
			borderHover: 'border-brand',
			bgDisabled: 'bg-tertiary',
			borderDisabled: 'border-secondary',
			onDisabled: 'text-quaternary',
			borderError: 'border-error',
		},

		toggle: {
			trackBg: 'bg-tertiary',
			trackBgChecked: 'bg-brand-solid',
			trackBorder: 'border-primary',
			thumbColor: 'text-white',
			thumbColorChecked: 'text-white',
			bgHover: 'bg-quaternary',
			trackBgCheckedHover: 'bg-brand-solid_hover',
			bgDisabled: 'bg-tertiary',
			trackBgDisabled: 'bg-quaternary',
			thumbDisabled: 'text-quaternary',
			borderError: 'border-error',
		},

		components: {
			buttonBorderRadii: { type: 'radii' as const, value: 'md' },
			cardBorderRadii: { type: 'radii' as const, value: 'lg' },
			saleCardRadii: { type: 'radii' as const, value: '3xl' },
			inputBorderRadii: { type: 'radii' as const, value: 'md' },

			headerBg: { dark: 'primary_950', light: 'primary_950' },
			headerAvatarBg: { dark: 'primary_600', light: 'primary_600' },
			footerBg: { dark: 'primary_950', light: 'primary_950' },
			footerBgSecondary: { dark: 'primary_950', light: 'primary_950' },
			salesCardBg: { light: 'white', dark: 'neutral_900' },
			appShellBg: { light: 'white', dark: 'neutral_950' },
		},
	},
};

const defaultTheme = TokensSchema.parse(defaultThemeTokens);

export default defaultTheme;
