import { create } from '@stylexjs/stylex';
import { roles, spacing, radii } from '@repo/ui-web-stylex/vars.stylex';

export const styles = create({
	pagination: {
		display: 'flex',
		alignItems: 'center',
		gap: 4,
	},
	pageBtn: {
		minWidth: 36,
		height: 36,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		fontSize: 13,
		fontWeight: 500,
		fontFamily: 'system-ui, -apple-system, sans-serif',
		borderRadius: radii.md,
		borderWidth: 1,
		borderStyle: 'solid',
		borderColor: roles.border,
		backgroundColor: roles.surface,
		color: roles.text,
		cursor: 'pointer',
		transitionProperty: 'background-color, border-color, color',
		transitionDuration: '150ms',
		padding: `0 ${spacing.sm}`,
		':hover': {
			backgroundColor: roles.surfaceAlt,
			borderColor: roles.borderStrong,
		},
	},
	pageBtnActive: {
		backgroundColor: roles.actionPrimaryBg,
		borderColor: roles.actionPrimaryBorder,
		color: roles.actionPrimaryFg,
		fontWeight: 700,
		':hover': {
			backgroundColor: roles.actionPrimaryBgHover,
		},
	},
	navBtn: {
		minWidth: 36,
		height: 36,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		fontSize: 16,
		fontFamily: 'system-ui, -apple-system, sans-serif',
		borderRadius: radii.md,
		borderWidth: 1,
		borderStyle: 'solid',
		borderColor: roles.border,
		backgroundColor: roles.surface,
		color: roles.textSecondary,
		cursor: 'pointer',
		transitionProperty: 'background-color, color',
		transitionDuration: '150ms',
		':hover': {
			backgroundColor: roles.surfaceAlt,
			color: roles.text,
		},
	},
	ellipsis: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		minWidth: 36,
		height: 36,
		fontSize: 13,
		color: roles.textTertiary,
	},
});
