import { create } from '@stylexjs/stylex';
import {
	fontFamily,
	typographyContracts,
	roles,
} from '../../adapters/stylex/createStylexVars.stylex';

export const roleStyles = create({
	heading1: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.heading1FontSize,
		fontWeight: typographyContracts.heading1FontWeight,
		lineHeight: typographyContracts.heading1LineHeight,
		letterSpacing: typographyContracts.heading1LetterSpacing,
		color: typographyContracts.heading1Color,
		margin: 0,
	},
	heading2: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.heading2FontSize,
		fontWeight: typographyContracts.heading2FontWeight,
		lineHeight: typographyContracts.heading2LineHeight,
		letterSpacing: typographyContracts.heading2LetterSpacing,
		color: typographyContracts.heading2Color,
		margin: 0,
	},
	heading3: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.heading3FontSize,
		fontWeight: typographyContracts.heading3FontWeight,
		lineHeight: typographyContracts.heading3LineHeight,
		letterSpacing: typographyContracts.heading3LetterSpacing,
		color: typographyContracts.heading3Color,
		margin: 0,
	},
	heading4: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.heading4FontSize,
		fontWeight: typographyContracts.heading4FontWeight,
		lineHeight: typographyContracts.heading4LineHeight,
		letterSpacing: typographyContracts.heading4LetterSpacing,
		color: typographyContracts.heading4Color,
		margin: 0,
	},
	body: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.bodyFontSize,
		fontWeight: typographyContracts.bodyFontWeight,
		lineHeight: typographyContracts.bodyLineHeight,
		letterSpacing: typographyContracts.bodyLetterSpacing,
		color: typographyContracts.bodyColor,
		margin: 0,
	},
	bodySm: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.bodySmFontSize,
		fontWeight: typographyContracts.bodySmFontWeight,
		lineHeight: typographyContracts.bodySmLineHeight,
		letterSpacing: typographyContracts.bodySmLetterSpacing,
		color: typographyContracts.bodySmColor,
		margin: 0,
	},
	caption: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.captionFontSize,
		fontWeight: typographyContracts.captionFontWeight,
		lineHeight: typographyContracts.captionLineHeight,
		letterSpacing: typographyContracts.captionLetterSpacing,
		color: typographyContracts.captionColor,
		margin: 0,
	},
	label: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.labelFontSize,
		fontWeight: typographyContracts.labelFontWeight,
		lineHeight: typographyContracts.labelLineHeight,
		letterSpacing: typographyContracts.labelLetterSpacing,
		color: typographyContracts.labelColor,
		margin: 0,
	},
	overline: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.overlineFontSize,
		fontWeight: typographyContracts.overlineFontWeight,
		lineHeight: typographyContracts.overlineLineHeight,
		letterSpacing: typographyContracts.overlineLetterSpacing,
		color: typographyContracts.overlineColor,
		textTransform: 'uppercase',
		margin: 0,
	},
});

export const colorStyles = create({
	text: { color: roles.text },
	textSecondary: { color: roles.textSecondary },
	textTertiary: { color: roles.textTertiary },
	textInverse: { color: roles.textInverse },
	textBrand: { color: roles.textBrand },
	primary: { color: roles.primary },
	secondary: { color: roles.secondary },
	errorFg: { color: roles.errorFg },
	successFg: { color: roles.successFg },
	warningFg: { color: roles.warningFg },
	infoFg: { color: roles.infoFg },
	inherit: { color: 'inherit' },
});
