import { create } from '@stylexjs/stylex';
import { fontFamily, typographyContracts } from '../../adapters/stylex/createStylexVars.stylex';

export const roleStyles = create({
	h1: {
		fontFamily: fontFamily.heading,
		fontSize: typographyContracts.h1FontSize,
		fontWeight: typographyContracts.h1FontWeight,
		lineHeight: typographyContracts.h1LineHeight,
		letterSpacing: typographyContracts.h1LetterSpacing,
		color: typographyContracts.h1Color,
		margin: 0,
	},
	h2: {
		fontFamily: fontFamily.heading,
		fontSize: typographyContracts.h2FontSize,
		fontWeight: typographyContracts.h2FontWeight,
		lineHeight: typographyContracts.h2LineHeight,
		letterSpacing: typographyContracts.h2LetterSpacing,
		color: typographyContracts.h2Color,
		margin: 0,
	},
	h3: {
		fontFamily: fontFamily.heading,
		fontSize: typographyContracts.h3FontSize,
		fontWeight: typographyContracts.h3FontWeight,
		lineHeight: typographyContracts.h3LineHeight,
		letterSpacing: typographyContracts.h3LetterSpacing,
		color: typographyContracts.h3Color,
		margin: 0,
	},
	h4: {
		fontFamily: fontFamily.heading,
		fontSize: typographyContracts.h4FontSize,
		fontWeight: typographyContracts.h4FontWeight,
		lineHeight: typographyContracts.h4LineHeight,
		letterSpacing: typographyContracts.h4LetterSpacing,
		color: typographyContracts.h4Color,
		margin: 0,
	},
	p: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.pFontSize,
		fontWeight: typographyContracts.pFontWeight,
		lineHeight: typographyContracts.pLineHeight,
		letterSpacing: typographyContracts.pLetterSpacing,
		color: typographyContracts.pColor,
		margin: 0,
	},
	caption: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.captionFontSize,
		fontWeight: typographyContracts.captionFontWeight,
		lineHeight: typographyContracts.captionLineHeight,
		letterSpacing: typographyContracts.captionLetterSpacing,
		color: typographyContracts.captionColor,
		margin: 0,
	},
	label: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.labelFontSize,
		fontWeight: typographyContracts.labelFontWeight,
		lineHeight: typographyContracts.labelLineHeight,
		letterSpacing: typographyContracts.labelLetterSpacing,
		color: typographyContracts.labelColor,
		margin: 0,
	},
	overline: {
		fontFamily: fontFamily.body,
		fontSize: typographyContracts.overlineFontSize,
		fontWeight: typographyContracts.overlineFontWeight,
		lineHeight: typographyContracts.overlineLineHeight,
		letterSpacing: typographyContracts.overlineLetterSpacing,
		color: typographyContracts.overlineColor,
		textTransform: 'uppercase',
		margin: 0,
	},
});

export const colorStyles = create({
	'text-primary': { color: 'var(--ct-text-primary)' },
	'text-secondary': { color: 'var(--ct-text-secondary)' },
	'text-tertiary': { color: 'var(--ct-text-tertiary)' },
	'text-quaternary': { color: 'var(--ct-text-quaternary)' },
	'text-white': { color: 'var(--ct-text-white)' },
	'text-placeholder': { color: 'var(--ct-text-placeholder)' },
	'text-brand-primary': { color: 'var(--ct-text-brand-primary)' },
	'text-brand-secondary': { color: 'var(--ct-text-brand-secondary)' },
	'text-brand-tertiary': { color: 'var(--ct-text-brand-tertiary)' },
	'text-error-primary': { color: 'var(--ct-text-error-primary)' },
	'text-warning-primary': { color: 'var(--ct-text-warning-primary)' },
	'text-success-primary': { color: 'var(--ct-text-success-primary)' },
	'text-info-primary': { color: 'var(--ct-text-info-primary)' },
	inherit: { color: 'inherit' },
});
