import { create } from '@stylexjs/stylex';
import {
	roles,
	spacing,
	components,
} from '../../../design-system/adapters/stylex/createStylexVars.stylex';

export const styles = create({
	section: {
		marginBottom: spacing.lg,
	},
	tag: {
		fontSize: 10,
		fontFamily: '"SF Mono", "Cascadia Code", monospace',
		color: roles.textSecondary,
		marginBottom: spacing.sm,
	},
	heading: {
		fontSize: 13,
		fontWeight: 600,
		textTransform: 'uppercase',
		letterSpacing: '0.5px',
		color: roles.textSecondary,
		marginBottom: spacing.sm,
	},
	form: {
		backgroundColor: roles.surface,
		borderWidth: 1,
		borderStyle: 'solid',
		borderColor: roles.border,
		borderRadius: components.cardBorderRadii,
		padding: spacing.lg,
		display: 'flex',
		flexDirection: 'column',
		gap: spacing.md,
		maxWidth: 360,
	},
	field: {
		display: 'flex',
		flexDirection: 'column',
		gap: spacing.sm,
	},
	label: {
		fontSize: 13,
		fontWeight: 600,
		color: roles.text,
	},
	input: {
		padding: spacing.md,
		fontSize: 14,
		fontFamily: 'system-ui, -apple-system, sans-serif',
		color: roles.text,
		backgroundColor: roles.surfaceSunken,
		borderWidth: 1,
		borderStyle: 'solid',
		borderColor: roles.border,
		borderRadius: components.buttonBorderRadii,
		outline: 'none',
		transitionProperty: 'border-color, box-shadow',
		transitionDuration: '150ms',
		'::placeholder': {
			color: roles.textPlaceholder,
			opacity: 1,
		},
		':focus': {
			borderColor: roles.focusRing,
			boxShadow: `0 0 0 3px ${roles.focusRing}`,
		},
	},
	textarea: {
		padding: spacing.md,
		fontSize: 14,
		fontFamily: 'system-ui, -apple-system, sans-serif',
		color: roles.text,
		backgroundColor: roles.surfaceSunken,
		borderWidth: 1,
		borderStyle: 'solid',
		borderColor: roles.border,
		borderRadius: components.buttonBorderRadii,
		outline: 'none',
		resize: 'vertical',
		minHeight: 80,
		transitionProperty: 'border-color, box-shadow',
		transitionDuration: '150ms',
		'::placeholder': {
			color: roles.textPlaceholder,
			opacity: 1,
		},
		':focus': {
			borderColor: roles.focusRing,
			boxShadow: `0 0 0 3px ${roles.focusRing}`,
		},
	},
	select: {
		padding: spacing.md,
		fontSize: 14,
		fontFamily: 'system-ui, -apple-system, sans-serif',
		color: roles.text,
		backgroundColor: roles.surfaceSunken,
		borderWidth: 1,
		borderStyle: 'solid',
		borderColor: roles.border,
		borderRadius: components.buttonBorderRadii,
		outline: 'none',
		cursor: 'pointer',
		transitionProperty: 'border-color, box-shadow',
		transitionDuration: '150ms',
		':focus': {
			borderColor: roles.focusRing,
			boxShadow: `0 0 0 3px ${roles.focusRing}`,
		},
	},
});
