/**
 * generate-contract-css.ts
 *
 * Reads the default theme's contracts and generates the Tailwind CSS bridge
 * entries for color contract fields. Non-color fields (numbers, radiiRefs)
 * are skipped since they're resolved directly by applyTheme.ts.
 *
 * Run: npx tsx packages/ui-web-tailwind/scripts/generate-contract-css.ts
 */

import defaultTheme from '@repo/themes/src/default';

function toKebab(s: string): string {
	return s.replace(/([A-Z])/g, '-$1').toLowerCase();
}

function isColorField(value: unknown): boolean {
	return typeof value === 'string';
}

function isNestedContract(preset: Record<string, any>): boolean {
	const firstVal = Object.values(preset)[0];
	return (
		firstVal && typeof firstVal === 'object' && !Array.isArray(firstVal) && !('type' in firstVal)
	);
}

const lines: string[] = [];
const { typography, ...restContracts } = defaultTheme.contracts;

for (const [contractName, preset] of Object.entries(restContracts)) {
	if (!preset || typeof preset !== 'object') continue;

	const contractLines: string[] = [];

	if (isNestedContract(preset as Record<string, any>)) {
		// Nested: actions.primary.bg → --color-action-primary-bg: var(--action-primary-bg);
		for (const [variant, fields] of Object.entries(preset as Record<string, Record<string, any>>)) {
			if (!fields || typeof fields !== 'object') continue;
			for (const [field, value] of Object.entries(fields)) {
				if (!isColorField(value)) continue;
				const prefix = `${contractName}-${variant}-${toKebab(field)}`;
				contractLines.push(`\t--color-${prefix}: var(--${prefix});`);
			}
		}
	} else {
		// Flat: inputField.bg → --color-inputfield-bg: var(--inputfield-bg);
		for (const [field, value] of Object.entries(preset as Record<string, any>)) {
			if (!isColorField(value)) continue;
			const prefix = `${contractName}-${toKebab(field)}`;
			contractLines.push(`\t--color-${prefix}: var(--${prefix});`);
		}
	}

	if (contractLines.length > 0) {
		lines.push(`\t/* ${contractName} contracts */`);
		lines.push(...contractLines);
	}
}

const output = `/* Auto-generated by scripts/generate-contract-css.ts — DO NOT EDIT */
@theme inline {
${lines.join('\n')}
}`;

// Write to stdout
console.log(output);
