import { create } from '@stylexjs/stylex';
import {
	fontFamily,
	typographyRoles,
	roles,
} from '../../../../design-system/adapters/stylex/createStylexVars.stylex';

export const roleStyles = create({
	heading1: {
		fontFamily: fontFamily.body,
		fontSize: typographyRoles.heading1FontSize,
		fontWeight: typographyRoles.heading1FontWeight,
		lineHeight: typographyRoles.heading1LineHeight,
		letterSpacing: typographyRoles.heading1LetterSpacing,
		color: typographyRoles.heading1Color,
		margin: 0,
	},
	heading2: {
		fontFamily: fontFamily.body,
		fontSize: typographyRoles.heading2FontSize,
		fontWeight: typographyRoles.heading2FontWeight,
		lineHeight: typographyRoles.heading2LineHeight,
		letterSpacing: typographyRoles.heading2LetterSpacing,
		color: typographyRoles.heading2Color,
		margin: 0,
	},
	heading3: {
		fontFamily: fontFamily.body,
		fontSize: typographyRoles.heading3FontSize,
		fontWeight: typographyRoles.heading3FontWeight,
		lineHeight: typographyRoles.heading3LineHeight,
		letterSpacing: typographyRoles.heading3LetterSpacing,
		color: typographyRoles.heading3Color,
		margin: 0,
	},
	heading4: {
		fontFamily: fontFamily.body,
		fontSize: typographyRoles.heading4FontSize,
		fontWeight: typographyRoles.heading4FontWeight,
		lineHeight: typographyRoles.heading4LineHeight,
		letterSpacing: typographyRoles.heading4LetterSpacing,
		color: typographyRoles.heading4Color,
		margin: 0,
	},
	body: {
		fontFamily: fontFamily.body,
		fontSize: typographyRoles.bodyFontSize,
		fontWeight: typographyRoles.bodyFontWeight,
		lineHeight: typographyRoles.bodyLineHeight,
		letterSpacing: typographyRoles.bodyLetterSpacing,
		color: typographyRoles.bodyColor,
		margin: 0,
	},
	bodySm: {
		fontFamily: fontFamily.body,
		fontSize: typographyRoles.bodySmFontSize,
		fontWeight: typographyRoles.bodySmFontWeight,
		lineHeight: typographyRoles.bodySmLineHeight,
		letterSpacing: typographyRoles.bodySmLetterSpacing,
		color: typographyRoles.bodySmColor,
		margin: 0,
	},
	caption: {
		fontFamily: fontFamily.body,
		fontSize: typographyRoles.captionFontSize,
		fontWeight: typographyRoles.captionFontWeight,
		lineHeight: typographyRoles.captionLineHeight,
		letterSpacing: typographyRoles.captionLetterSpacing,
		color: typographyRoles.captionColor,
		margin: 0,
	},
	label: {
		fontFamily: fontFamily.body,
		fontSize: typographyRoles.labelFontSize,
		fontWeight: typographyRoles.labelFontWeight,
		lineHeight: typographyRoles.labelLineHeight,
		letterSpacing: typographyRoles.labelLetterSpacing,
		color: typographyRoles.labelColor,
		margin: 0,
	},
	overline: {
		fontFamily: fontFamily.body,
		fontSize: typographyRoles.overlineFontSize,
		fontWeight: typographyRoles.overlineFontWeight,
		lineHeight: typographyRoles.overlineLineHeight,
		letterSpacing: typographyRoles.overlineLetterSpacing,
		color: typographyRoles.overlineColor,
		textTransform: 'uppercase',
		margin: 0,
	},
});

export const colorStyles = create({
	text: { color: roles.text },
	textSecondary: { color: roles.textSecondary },
	textTertiary: { color: roles.textTertiary },
	textInverse: { color: roles.textInverse },
	textBrand: { color: roles.textBrand },
	primary: { color: roles.primary },
	secondary: { color: roles.secondary },
	errorFg: { color: roles.errorFg },
	successFg: { color: roles.successFg },
	warningFg: { color: roles.warningFg },
	infoFg: { color: roles.infoFg },
	inherit: { color: 'inherit' },
});
